services:
  be-rdz-th:
    image: node:20
    container_name: be-rdz-th
    restart: always
    working_dir: /app
    ports:
      - 5002:5002
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
    command: sh -c "npm install && npm start"
    networks:
      - rdz-th-network

networks:
  rdz-th-network:
    driver: bridge
